# Generated by Django 4.2.2 on 2023-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='team_pics')),
                ('head', models.CharField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
    ]
